default_twitter: &default_twitter
  twitter_api_key: gvt2LkYfcSVvRJrCMUSrWQufe #'先ほど取得したAPI key'
  twitter_api_secret: nqj8xvxt7iMPHQbFjvHPVMjhrSJTcvCSld6AI9JPMzEMC6ZIrR
 #'先ほど取得したAPI secret'

development:
  secret_key_base: 39e0d3ee8572bc7615fed4f0cf1884c1bbdb743d90a1bf52c351b80f008652b3b53ccd3b36022821ad1dd1178d358426089c7b27a35379dac790df8a53e47bd4 #長い文字列
  <<: *default_twitter

test:
  secret_key_base: 39e0d3ee8572bc7615fed4f0cf1884c1bbdb743d90a1bf52c351b80f008652b3b53ccd3b36022821ad1dd1178d358426089c7b27a35379dac790df8a53e47bd4 #長い文字列
  <<: *default_twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>